export const CONSTRAINTS = {
     TYPO_VARS :{
    H: {
      H_1: 'h1', 
      H_2: 'h2',
      H_3: 'h3', 
      H_4: 'h4',
      H_5: 'h5',
      H_6: 'h6', 
    },
    SUB: {
      S_1: 'subtitle1',
      S_2: 'subtitle2', 
    },
    BODY: {
      B_1: 'body1',
      B_2: 'body2', 
      INHERIT: 'inherit', 
    },
  },
   BOX_VARS : {
    E: {
      D: 'div',
      H: 'header',
      F: 'footer',
      S: 'section',
      A: 'aside',
      N: 'nav',
      ART: 'article',
      M: 'main',
      FRM: 'form',
      I: 'img',
      P: 'p',
      H1: 'h1',
      H2: 'h2',
      H3: 'h3',
      H4: 'h4',
      H5: 'h5',
      H6: 'h6',
      SP: 'span',
      ACH: 'a',
      UL: 'ul',
      OL: 'ol',
      LI: 'li',
      T: 'table',
      TH: 'th',
      TD: 'td',
      L: 'label',
      IN: 'input',
      BTN: 'button',
      STC: 'select',
      TAREA: 'textarea',
      VIO: 'video',
      AIO: 'audio',
      DT: 'details',
      SUM: 'summary',
      DLG: 'dialog',
      OUT: 'output',
      O: 'outline',
    },
  }
}